# pylint: disable=invalid-name,no-member
"""add_oauth_data_to_users

Revision ID: 2a768f035d17
Revises: a96ce0900295
Create Date: 2026-01-04 20:51:09.177470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a768f035d17"
down_revision: Union[str, Sequence[str], None] = "a96ce0900295"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("slack_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("idv_status", sa.String(), nullable=True))
    op.add_column("users", sa.Column("ysws_eligible", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["slack_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "ysws_eligible")
    op.drop_column("users", "idv_status")
    op.drop_column("users", "slack_id")
    # ### end Alembic commands ###
