# pylint: disable=invalid-name,no-member
"""add_project_description_field

Revision ID: 55c51de7e409
Revises: bc017ab47b46
Create Date: 2026-01-12 12:26:51.799061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55c51de7e409"
down_revision: Union[str, Sequence[str], None] = "bc017ab47b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
