# pylint: disable=invalid-name,no-member
"""update_ysws_eligible_to_bool

Revision ID: 7c7e7bd6fb71
Revises: 529e7822f1fd
Create Date: 2026-01-05 22:21:55.925496

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "7c7e7bd6fb71"
down_revision: Union[str, Sequence[str], None] = "529e7822f1fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
