# pylint: disable=invalid-name,no-member
"""Add referral_code_used

Revision ID: a96ce0900295
Revises: d7462fdbad39
Create Date: 2025-12-31 19:51:40.803978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96ce0900295'
down_revision: Union[str, Sequence[str], None] = 'd7462fdbad39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('referral_code_used', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'referral_code_used')
    # ### end Alembic commands ###
