# pylint: disable=invalid-name,no-member
"""update_ysws_eligible_to_bool_again

Revision ID: bc017ab47b46
Revises: 7c7e7bd6fb71
Create Date: 2026-01-05 22:26:03.473576

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bc017ab47b46"
down_revision: Union[str, Sequence[str], None] = "7c7e7bd6fb71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to convert VARCHAR to BOOLEAN with explicit casting
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN ysws_eligible TYPE BOOLEAN 
        USING CASE 
            WHEN ysws_eligible IS NULL THEN NULL
            WHEN LOWER(ysws_eligible) IN ('true', 't', 'yes', '1') THEN TRUE
            ELSE FALSE
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert boolean back to varchar
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN ysws_eligible TYPE VARCHAR 
        USING CASE 
            WHEN ysws_eligible IS NULL THEN NULL
            WHEN ysws_eligible = TRUE THEN 'true'
            ELSE 'false'
        END
    """)
    # ### end Alembic commands ###
