# pylint: disable=invalid-name,no-member,unused-import
"""Cleanup

Revision ID: d7462fdbad39
Revises: 96aca6c51a90
Create Date: 2025-12-17 20:19:36.347872

"""
from typing import Sequence, Union

from alembic import op # type: ignore # noqa: F401
import sqlalchemy as sa # type: ignore # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'd7462fdbad39'
down_revision: Union[str, Sequence[str], None] = '96aca6c51a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique') # type: ignore
    # ### end Alembic commands ###
