# pylint: disable=invalid-name,no-member
"""change_state_to_str

Revision ID: ff2ce0fad2ca
Revises: 55c51de7e409
Create Date: 2026-01-12 19:35:16.609218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2ce0fad2ca'
down_revision: Union[str, Sequence[str], None] = '55c51de7e409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devlogs', 'state',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    
    op.execute("UPDATE devlogs SET state = 'Pending'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE devlogs SET state = '0'")
    
    # Change column type back to INTEGER
    op.alter_column('devlogs', 'state',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
